FROM httpd:2.4
COPY . /usr/local/apache2/htdocs/
# RUN  apt-get update && apt-get install -y  software-properties-common 
# RUN  add-apt-repository ppa:deadsnakes/ppa 
# RUN  apt-get install -y python3.7 python3-pip && python3.7 --version
# WORKDIR /usr/local/apache2/htdocs
# #RUN ls *
# RUN  pip3 install -r requirements.txt
# RUN  python3 interpolation.py
